### ISSUE TITLE
Add the Super-Linter

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#112]
https://github.com/super-linter/super-linter

**Comment by dhirajchaurasiya10** [comment]
@jbampton Can you explain about the things to do under this issue

**Comment by jbampton** [comment]
https://github.com/super-linter/super-linter

Add the Super-Linter to the GitHub CI with Actions

**Comment by jbampton** [comment]
See we added it here

https://github.com/brisbanesocialchess/.github/blob/main/.github/workflows/linter.yml

**Comment by dhirajchaurasiya10** [comment]
@jbampton I did some changes regarding this issue. Do review once
