### ISSUE TITLE
Add `yamllint` to `pre-commit`

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#15]

**Comment by jbampton** [comment]
Hey @aniruddhaadak80 can you please just comment here on this issue saying you want it ?

I can then assign you.  Thanks

**Comment by aniruddhaadak80** [comment]
Can you please tell me what is the problem i.e for my work ?

**Comment by aniruddhaadak80** [comment]
> Hey @aniruddhaadak80 can you please just comment here on this issue saying you want it ?
> 
> I can then assign you. Thanks

Yes , I want this issue #4 . Please give me little bit details about this issue ?

**Comment by jbampton** [comment]
Thanks mate :+1: 

Just assigned here now all done
