### ISSUE TITLE
Add `.codespellrc` file in repo root folder

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#23]

**Comment by aniruddhaadak80** [comment]
Assign this issue to me @jbampton  , I am working on this .

**Comment by jbampton** [comment]
You are now assigned @aniruddhaadak80 thanks

**Comment by aniruddhaadak80** [comment]
Please review this #29 , and let me know if there is aything you want to change about  . Thank you .
