### ISSUE TITLE
Broken pull request labeler

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#28]
PR labeler run seen here:

https://github.com/brisbanesocialchess/awesome-social-chess/actions/runs/11540164586/job/32120660661?pr=27

**Comment by smriad** [comment]
@jbampton Assign this to me

**Comment by jbampton** [comment]
Sounds great but you already have two open issues assigned.  

If you fix the two existing issues you can have this issue if it is still open.

Thanks.

**Comment by jbampton** [comment]
Thanks @smriad you are now assigned

**Comment by jbampton** [comment]
Fixed by #51
