### ISSUE TITLE
Add `.gitattributes` file to handle line endings

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#32]
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by aniruddhaadak80** [comment]
Please assign this to me @jbampton .

**Comment by jbampton** [comment]
Showing great enthusiasm @aniruddhaadak80 :)

I just assigned you to the other issue.

Let us solve one issue at a time.

If you solve the other issue you can have this issue if it is still open.

Thanks.
