### ISSUE TITLE
Add the pull request labeler

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#4]

**Comment by aniruddhaadak80** [comment]
Can you give me little bit more details about this issue  ?
Assign me this issue please @jbampton  .After that I can work on this .

**Comment by jbampton** [comment]
Hey @aniruddhaadak80 

Please add your comment to this issue first:

https://github.com/brisbanesocialchess/awesome-social-chess/issues/15

I need to assign you for the work you did.  Just some admin work.

**Comment by aniruddhaadak80** [comment]
Can you give me little bit more details about this issue ?

**Comment by jbampton** [comment]
https://github.com/actions/labeler

Examples here:

https://github.com/SalamLang/Salam/blob/main/.github/labeler.yml

https://github.com/SalamLang/Salam/blob/main/.github/workflows/pr-labeler.yml

**Comment by aniruddhaadak80** [comment]
Okey , I am fixing this .

**Comment by jbampton** [comment]
Hey @aniruddhaadak80 I sent you an invite to join Brisbane Social Chess Organization on GitHub.

It is safe to join and we invite all contributors.

**Comment by aniruddhaadak80** [comment]
Please review this #24 and tell me if you want any change here .

**Comment by aniruddhaadak80** [comment]
> Hey @aniruddhaadak80 I sent you an invite to join Brisbane Social Chess Organization on GitHub.
> 
> It is safe to join and we invite all contributors.

Hello @jbampton ,

Thank you for the invitation to join the Brisbane Social Chess Organization. I’m honored to be considered and appreciate the opportunity to contribute further to the project.

I’ll review the invite and join shortly. Looking forward to continued collaboration!

Best regards,
Aniruddha Adak

**Comment by jbampton** [comment]
Thanks for joining Brisbane Social Chess @aniruddhaadak80 :1st_place_medal: 

You can also make your new organization status `public` on the `people` page here:

https://github.com/orgs/brisbanesocialchess/people

If you currently check your GitHub profile when logged out or in a private window or incognito window your new organization status won't display by default since it is marked private.

If you want to show your GitHub organizations to the public on your GitHub profile you need to change to `public`.

Thanks once again
