### ISSUE TITLE
Add `gitleaks` to `pre-commit`

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#53]
https://github.com/gitleaks/gitleaks?tab=readme-ov-file#pre-commit

**Comment by Virtual4087** [comment]
I would like to do this

**Comment by jbampton** [comment]
Let us do one issue at a time. Thanks

**Comment by jbampton** [comment]
You are now assigned @Virtual4087

**Comment by Virtual4087** [comment]
@jbampton I am supposed to create a pre-commit-config.yaml file in the same dir as precommit.yml and add the repo section of gitleaks inside it right?

**Comment by jbampton** [comment]
https://github.com/brisbanesocialchess/awesome-social-chess/blob/main/.pre-commit-config.yaml

We already have a pre-commit config file.  Just add the gitleaks section.

Thanks

**Comment by Virtual4087** [comment]
Ohh my bad didn't see it
