### ISSUE TITLE
Add Dependabot config for `github-actions` as `daily`

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#58]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

**Comment by aniruddhaadak80** [comment]
Assign me this  please @jbampton . I am working on this

**Comment by jbampton** [comment]
Thanks @aniruddhaadak80 you are now assigned :+1:

**Comment by aniruddhaadak80** [comment]
Please review #84 .
