### ISSUE TITLE
Need new image for this repos social preview

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#61]
![Screenshot from 2024-10-28 05-35-59](https://github.com/user-attachments/assets/3a9aa05d-c52b-4d03-87d7-bba1bdd5c7a7)

**Comment by TylrDn** [comment]
Definetly want this to be assigned to me and will be sure to use an image different than the README

**Comment by jbampton** [comment]
Let us only work on one issue at a time.

You have one issue assigned already.  If you finish that and this is still open we can assign you.

Thanks.
