### ISSUE TITLE
Delete an image file

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#63]
https://github.com/brisbanesocialchess/awesome-social-chess/blob/main/assets/Social%20Chess%20Logo.png

**Comment by TylrDn** [comment]
Following up to ask you assign me this issue. I am aware of the duplicate assets.

**Comment by jbampton** [comment]
Let us only work on one issue at a time.

You have one issue assigned already.  If you finish that and this is still open we can assign you.

Thanks.

**Comment by Virtual4087** [comment]
Can i get assigned?

**Comment by jbampton** [comment]
Thanks @Virtual4087 you are now assigned
