### ISSUE TITLE
Repo social preview image must be below 1 MB

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/awesome-social-chess#93]
https://github.com/brisbanesocialchess/awesome-social-chess/blob/main/assets/social-preview.png

**Comment by jbampton** [comment]
![Screenshot from 2024-10-29 23-19-55](https://github.com/user-attachments/assets/275ca4c3-ca87-4307-a442-6e90334a368f)

**Comment by BaseMax** [comment]
done, will shoot a merge request.

**Comment by BaseMax** [comment]
https://github.com/brisbanesocialchess/awesome-social-chess/pull/128

**Comment by jbampton** [comment]
Thanks :+1:
